# Generated by Django 3.2.4 on 2021-06-16 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='request_message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('required_concepts', models.CharField(max_length=250)),
                ('minimum_concepts', models.CharField(max_length=250)),
                ('table_dimensions', models.CharField(max_length=100)),
                ('youtube_link', models.CharField(max_length=250)),
                ('form_link', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulators',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
