# Generated by Django 3.2.4 on 2021-06-16 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0002_auto_20210616_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simulador',
            new_name='Simulator',
        ),
    ]
