# Generated by Django 3.2.4 on 2021-06-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('professor', '0003_rename_simulador_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulators',
                                    to='professor.profile'),
        ),
    ]
